sudo: required
dist: trusty

language: node_js
node_js:
  - "10"

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
